spring:
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 15
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
    password: root
    url: jdbc:postgresql://127.0.0.1:5432/bookstore
    username: postgres
  jpa:
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  security:
    user:
      name: test
      password: test
