/*
CREATE DATABASE bookstore;
DROP DATABASE bookstore
*/

/*
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS "covers";
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS role;
*/

CREATE TABLE IF NOT EXISTS "covers" (
	cover_id BIGSERIAL PRIMARY KEY,
	"name" VARCHAR (10) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS books (
    book_id BIGSERIAL PRIMARY KEY,
    title VARCHAR (75) NOT NULL,
    author VARCHAR (35) NOT NULL,
    isbn VARCHAR (30) NOT NULL,
    pages INT2,
    price NUMERIC(6,2),
    cover_id BIGINT NOT NULL REFERENCES "covers",
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS "role" (
	role_id BIGSERIAL PRIMARY KEY,
	"name" VARCHAR (10) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    user_id BIGSERIAL PRIMARY KEY,
    first_name VARCHAR (30),
    last_name VARCHAR (30),
    email VARCHAR (40) NOT NULL,
    "password" VARCHAR (40) NOT NULL,
    role_id BIGINT NOT NULL REFERENCES ROLE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);
